const KEY='memoriaLector.v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{books:[],activeBookId:null};
let deferredInstall=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const active=()=>state.books.find(b=>b.id===state.activeBookId);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const modal=(html)=>{document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden')};
const close=()=>document.getElementById('modal').classList.add('hidden');
const toast=(msg)=>{const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add('hidden'),2200)};
document.getElementById('closeModal').onclick=close;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')close()};

// --- V5 data migration -----------------------------------------------------
const REL_CATALOG={
 'madre de':{mode:'directed',category:'Familia'},'padre de':{mode:'directed',category:'Familia'},'hijo/a de':{mode:'directed',category:'Familia'},'hermano de':{mode:'symmetric',category:'Familia'},'hermana de':{mode:'symmetric',category:'Familia'},'primo/a de':{mode:'symmetric',category:'Familia'},'tío/a de':{mode:'directed',category:'Familia'},'esposo/a de':{mode:'symmetric',category:'Romance'},'pareja de':{mode:'symmetric',category:'Romance'},'jefe de':{mode:'directed',category:'Trabajo'},'empleado/a de':{mode:'directed',category:'Trabajo'},'profesor/a de':{mode:'directed',category:'Académica / Mentoría'},'estudiante de':{mode:'directed',category:'Académica / Mentoría'},'amigo/a de':{mode:'symmetric',category:'Amistad'},'enemigo/a de':{mode:'symmetric',category:'Conflicto'},'mentor de':{mode:'directed',category:'Académica / Mentoría'},'socio/a de':{mode:'symmetric',category:'Trabajo'},'conocido/a de':{mode:'symmetric',category:'Amistad'},'colega de':{mode:'symmetric',category:'Trabajo'},'rival de':{mode:'symmetric',category:'Conflicto'},'otra relación':{mode:'directed',category:'Otra'}
};
const relTypes=Object.keys(REL_CATALOG);
const inferRel=(label)=>REL_CATALOG[label]||{mode:'directed',category:'Otra'};
function migrate(){
 state.books=(state.books||[]).map(b=>{
   b.characters=b.characters||[];b.relationships=b.relationships||[];b.quotes=b.quotes||[];b.sessions=b.sessions||[];
   b.characters.forEach(c=>{c.shortName=c.shortName||'';c.firstChapter=c.firstChapter??c.chapter??''});
   b.sessions.forEach(s=>{
     // Preserve V5 sessions while giving them the richer session structure.
     s.sessionType=s.sessionType||'chapter';s.plot=s.plot??s.summary??'';s.impression=s.impression??s.note??'';
      s.characterIds=Array.isArray(s.characterIds)?s.characterIds:[];s.relationshipIds=Array.isArray(s.relationshipIds)?s.relationshipIds:(s.relationshipId?[s.relationshipId]:[]);s.quoteIds=Array.isArray(s.quoteIds)?s.quoteIds:[];delete s.relationshipId;
     s.context=s.context||'';s.pointStart=s.pointStart||'';s.pointEnd=s.pointEnd||'';
     if(!s.pointEnd&&s.chapter)s.pointEnd=`Capítulo ${s.chapter}${s.page?` · pág. ${s.page}`:''}`;
     s.date=s.date||new Date().toLocaleString('es-CR');
   });
   b.relationships.forEach(r=>{
     if(!r.types&&r.type)r.types=[r.type];
     if(!Array.isArray(r.types)||!r.types.length)r.types=['otra relación'];
     r.items=(r.items&&Array.isArray(r.items))?r.items:r.types.map(label=>({label,mode:inferRel(label).mode,category:inferRel(label).category}));
     // V4 had a custom relation stored in types. Preserve it.
     r.items=r.items.map(it=>({label:it.label||it.name||'otra relación',mode:it.mode||inferRel(it.label||it.name||'otra relación').mode,category:it.category||inferRel(it.label||it.name||'otra relación').category}));
     r.types=r.items.map(it=>it.label);
     delete r.type;
   });
   return b;
 });
 save();
}
migrate();

function view(name){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));render(name)}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>view(b.dataset.view));
function render(name='home'){if(name==='home')renderHome();if(name==='characters')renderCharacters();if(name==='map')renderMap();if(name==='quotes')renderQuotes();if(name==='sessions')renderSessions();if(name==='recap')renderRecap()}
function requireBook(){if(!active()){view('home');return false}return true}
function selectBook(id){state.activeBookId=id;save();view('recap')}

// --- Books -----------------------------------------------------------------
function sessionPoint(s){return s?.pointEnd||s?.pointStart||(s?.chapter?`Capítulo ${s.chapter}${s.page?` · pág. ${s.page}`:''}`:'Punto no registrado')}
function sessionBrief(s){return s?.plot||s?.summary||''}
function renderHome(){const app=document.getElementById('app');if(!state.books.length){app.innerHTML=`<div class="card hero"><h2>Bienvenido a tu memoria de lectura.</h2><p class="muted">Registra libros, personajes, relaciones, sesiones y fragmentos. Todo queda guardado en este dispositivo.</p><div class="actions"><button class="primary" onclick="newBook()">+ Añadir mi primer libro</button></div></div>`;return}app.innerHTML=`<div class="section-title"><div><h2>Mis libros</h2><div class="muted">${state.books.length} libro(s)</div></div><button class="primary" onclick="newBook()">+ Libro</button></div><div class="grid">${state.books.map(b=>{const last=b.sessions?.at(-1);return `<div class="card"><div class="book-row"><div class="book-cover">📖</div><div><h3>${esc(b.title)}</h3><div class="muted">${esc(b.author||'Autor no registrado')}</div><div class="tag">${b.sessions?.length||0} sesión(es)</div></div></div>${last?`<div class="hint"><strong>Última sesión de lectura</strong><br>${esc(last.date)} · ${esc(sessionPoint(last))}${sessionBrief(last)?`<br>${esc(sessionBrief(last).slice(0,120))}${sessionBrief(last).length>120?'…':''}`:''}</div>`:`<div class="muted">Aún no hay sesiones registradas.</div>`}<div class="actions"><button class="primary" onclick="selectBook('${b.id}')">${last?'Retomar lectura':'Abrir'}</button><button class="secondary" onclick="editBook('${b.id}')">Editar</button></div></div>`}).join('')}</div>`}
function newBook(){modal(`<h2>Nuevo libro</h2><form onsubmit="createBook(event)"><div class="field"><label>Título</label><input name="title" required></div><div class="field"><label>Autor</label><input name="author"></div><div class="field"><label>Notas iniciales</label><textarea name="notes" placeholder="¿Por qué lo estás leyendo?"></textarea></div><button class="primary">Crear libro</button></form>`)}
function createBook(e){e.preventDefault();const f=new FormData(e.target);const b={id:uid(),title:f.get('title'),author:f.get('author'),notes:f.get('notes'),characters:[],relationships:[],quotes:[],sessions:[]};state.books.push(b);state.activeBookId=b.id;save();close();view('recap')}
function editBook(id){const b=state.books.find(x=>x.id===id);modal(`<h2>Editar libro</h2><form onsubmit="updateBook(event,'${id}')"><div class="field"><label>Título</label><input name="title" value="${esc(b.title)}" required></div><div class="field"><label>Autor</label><input name="author" value="${esc(b.author)}"></div><div class="field"><label>Notas</label><textarea name="notes">${esc(b.notes)}</textarea></div><button class="primary">Guardar</button></form>`)}
function updateBook(e,id){e.preventDefault();const b=state.books.find(x=>x.id===id),f=new FormData(e.target);b.title=f.get('title');b.author=f.get('author');b.notes=f.get('notes');save();close();renderHome()}

// --- Characters ------------------------------------------------------------
function renderCharacters(){if(!requireBook())return;const b=active();document.getElementById('app').innerHTML=`<div class="section-title"><div><h2>👥 Personajes</h2><div class="muted">${esc(b.title)}</div></div><div class="actions"><button class="secondary" onclick="characterDuplicateDiagnostics()">🔍 Revisar duplicados</button><button class="primary" onclick="newCharacter()">+ Personaje</button></div></div><div class="grid">${b.characters.length?b.characters.map(c=>`<div class="card"><h3>${esc(c.name)}</h3><div class="node-name-preview">Mapa: <strong>${esc(displayName(c))}</strong></div><div class="muted">${esc(c.description||'Sin descripción')}</div><div class="tag">Primera aparición: ${esc(c.firstChapter||'?')}</div><div class="actions"><button class="secondary" onclick="editCharacter('${c.id}')">Editar</button></div></div>`).join(''):`<div class="empty">Aún no has registrado personajes.</div>`}</div><div class="card" style="margin-top:14px"><div class="section-title"><div><h3>🔗 Relaciones</h3><div class="muted">Una misma conexión puede tener varias relaciones.</div></div><button class="secondary" onclick="newRelationship()">+ Relación</button></div>${b.relationships.length?`<div class="list">${b.relationships.map(r=>relationshipRow(b,r)).join('')}</div>`:`<div class="muted">Conecta personajes como madre, hermano, jefe, profesor, amigo, enemigo, etc.</div>`}</div>`}
function displayName(c){if(!c)return'?';const n=(c.shortName||'').trim();if(n)return n;const full=c.name||'?';if(full.length<=20)return full;return full.slice(0,18).trimEnd()+'…'}
function newCharacter(){modal(`<h2>Nuevo personaje</h2><form onsubmit="createCharacter(event)"><div class="field"><label>Nombre completo</label><input name="name" required></div><div class="field"><label>Nombre corto para el mapa <span class="muted">(opcional)</span></label><input name="shortName" placeholder="Ej.: Don Basilio"></div><div class="hint">Si no escribes un nombre corto, el mapa abreviará automáticamente los nombres demasiado largos. Al pasar el mouse sobre el nodo podrás ver el nombre completo.</div><div class="field"><label>Descripción / cómo lo recuerdas</label><textarea name="description"></textarea></div><div class="field"><label>Primera aparición (capítulo)</label><input name="chapter" type="number" min="0"></div><button class="primary">Guardar personaje</button></form>`)}
function createCharacter(e){e.preventDefault();const f=new FormData(e.target);active().characters.push({id:uid(),name:f.get('name'),shortName:f.get('shortName'),description:f.get('description'),firstChapter:f.get('chapter')});save();close();renderCharacters()}
function editCharacter(id){const c=active().characters.find(x=>x.id===id);modal(`<h2>Editar personaje</h2><form onsubmit="updateCharacter(event,'${id}')"><div class="field"><label>Nombre completo</label><input name="name" value="${esc(c.name)}" required></div><div class="field"><label>Nombre corto para el mapa</label><input name="shortName" value="${esc(c.shortName||'')}" placeholder="Opcional"></div><div class="field"><label>Descripción</label><textarea name="description">${esc(c.description)}</textarea></div><div class="field"><label>Primera aparición (capítulo)</label><input name="chapter" type="number" value="${esc(c.firstChapter)}"></div><button class="primary">Guardar</button></form>`)}
function updateCharacter(e,id){e.preventDefault();const c=active().characters.find(x=>x.id===id),f=new FormData(e.target);c.name=f.get('name');c.shortName=f.get('shortName');c.description=f.get('description');c.firstChapter=f.get('chapter');save();close();renderCharacters()}
function normalizeCharacterText(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('es').replace(/\s+/g,' ')}
function characterRelationsFor(b,id){return b.relationships.filter(r=>r.from===id||r.to===id)}
function characterSessionsFor(b,id){return b.sessions.filter(s=>(s.characterIds||[]).includes(id))}
function characterDuplicateGroups(){
 const b=active(),groups=new Map();
 b.characters.forEach(c=>{
   const nameKey=normalizeCharacterText(c.name),shortKey=normalizeCharacterText(c.shortName);
   const key=nameKey?`name:${nameKey}`:(shortKey?`short:${shortKey}`:'');
   if(!key)return;
   groups.set(key,[...(groups.get(key)||[]),c]);
 });
 return [...groups.values()].filter(g=>g.length>1);
}
function characterDuplicateDiagnostics(){
 const b=active(),groups=characterDuplicateGroups();
 if(!groups.length){modal('<h2>🔍 Revisar personajes duplicados</h2><div class="empty">No se detectaron posibles duplicados por nombre.</div><div class="actions"><button class="secondary" onclick="close()">Cerrar</button></div>');return}
 const rows=groups.map((group,i)=>{
   const cards=group.map(c=>{const rs=characterRelationsFor(b,c.id),ss=characterSessionsFor(b,c.id);return `<div class="card"><h3>${esc(c.name||'?')}</h3><div class="muted">ID: ${esc(c.id)}</div><p>${esc(c.description||'Sin descripción')}</p><div><span class="tag">${rs.length} relación(es)</span><span class="tag">${ss.length} sesión(es)</span><span class="tag">Primera aparición: ${esc(c.firstChapter||'?')}</span></div><div class="actions"><button class="secondary" onclick="editCharacter('${c.id}')">Ver / editar</button></div></div>`}).join('');
   return `<div class="item"><h3>⚠️ Posible duplicado ${i+1}</h3><div class="grid">${cards}</div><div class="actions"><button class="secondary" onclick="compareCharacters('${group[0].id}','${group[1].id}')">Comparar</button><button class="primary" onclick="openCharacterMerge('${group[0].id}','${group[1].id}')">Fusionar</button><button class="secondary" onclick="toast('Coincidencia ignorada por ahora')">Ignorar</button></div></div>`;
 }).join('');
 modal(`<h2>🔍 Revisar personajes duplicados</h2><p class="muted">Se detectan coincidencias por nombre normalizado. No se fusiona nada automáticamente.</p><div class="list">${rows}</div><div class="actions"><button class="secondary" onclick="close()">Cerrar</button></div>`);
}
function characterSummary(b,c){return {relations:characterRelationsFor(b,c.id).length,sessions:characterSessionsFor(b,c.id).length,firstChapter:c.firstChapter||'',name:c.name||'',shortName:c.shortName||'',description:c.description||''}}
function setMergeSource(id){const b=active(),c=b.characters.find(x=>x.id===id);if(!c)return;const form=document.querySelector('#modalBody form');if(!form)return;['name','shortName','description','firstChapter'].forEach(k=>{const el=form.elements[k];if(el)el.value=c[k]||''});}
function compareCharacters(aid,bid){
 const b=active(),a=b.characters.find(c=>c.id===aid),z=b.characters.find(c=>c.id===bid);if(!a||!z)return;
 const card=c=>{const x=characterSummary(b,c);return `<div class="card"><h3>${esc(x.name)}</h3><div class="muted">ID: ${esc(c.id)}</div><p><strong>Nombre corto:</strong> ${esc(x.shortName||'—')}</p><p><strong>Descripción:</strong> ${esc(x.description||'—')}</p><p><strong>Primera aparición:</strong> ${esc(x.firstChapter||'?')}</p><p><strong>Relaciones:</strong> ${x.relations}</p><p><strong>Sesiones:</strong> ${x.sessions}</p></div>`};
 modal(`<h2>Comparar personajes</h2><div class="grid">${card(a)}${card(z)}</div><div class="actions"><button class="secondary" onclick="openCharacterMerge('${aid}','${bid}')">Fusionar estos registros</button><button class="secondary" onclick="characterDuplicateDiagnostics()">Volver</button></div>`);
}
function openCharacterMerge(aid,bid){
 const b=active(),a=b.characters.find(c=>c.id===aid),z=b.characters.find(c=>c.id===bid);if(!a||!z)return;
 const field=(name,label)=>`<div class="field"><label>${label}</label><input name="${name}" value="${esc(a[name]||'')}"></div>`;
 modal(`<h2>🔗 Fusionar personajes</h2><div class="notice">Vas a fusionar <strong>${esc(a.name)}</strong> con <strong>${esc(z.name)}</strong>. Esta acción actualizará relaciones, sesiones y el mapa. No se realizará hasta confirmar.</div><form onsubmit="mergeCharacters(event,'${aid}','${bid}')"><div class="field"><label>Personaje que se conservará</label><div class="check-grid"><label class="check-option"><input type="radio" name="keep" value="${aid}" checked onchange="setMergeSource('${aid}')"> ${esc(a.name)}</label><label class="check-option"><input type="radio" name="keep" value="${bid}" onchange="setMergeSource('${bid}')"> ${esc(z.name)}</label></div></div><div class="grid">${field('name','Nombre final')}<div class="field"><label>Nombre corto final</label><input name="shortName" value="${esc(a.shortName||z.shortName||'')}"></div></div><div class="field"><label>Descripción final</label><textarea name="description">${esc(a.description||z.description||'')}</textarea></div><div class="grid"><div class="field"><label>Primera aparición final</label><input name="firstChapter" type="number" min="0" value="${esc(a.firstChapter||z.firstChapter||'')}"></div><div class="field"><label>Confirmación</label><select name="confirm"><option value="no">No fusionar</option><option value="yes">Sí, fusionar</option></select></div></div><div class="hint">Las relaciones y sesiones de ambos registros se conservarán. Las relaciones equivalentes se consolidarán y las diferentes etiquetas se mantendrán en una misma conexión cuando corresponda.</div><button class="primary">Fusionar personajes</button></form>`);
}
function mergeCharacters(e,aid,bid){
 e.preventDefault();const f=new FormData(e.target);if(f.get('confirm')!=='yes'){toast('Fusión cancelada');return}
 const b=active(),a=b.characters.find(c=>c.id===aid),z=b.characters.find(c=>c.id===bid);if(!a||!z)return;
 const keepId=f.get('keep'),removeId=keepId===aid?bid:aid,keep=b.characters.find(c=>c.id===keepId),remove=b.characters.find(c=>c.id===removeId);if(!keep||!remove)return;
 const oldIds=new Set([aid,bid]);
 keep.name=String(f.get('name')||keep.name||remove.name).trim();keep.shortName=String(f.get('shortName')||'').trim();keep.description=String(f.get('description')||'').trim();keep.firstChapter=f.get('firstChapter')||keep.firstChapter||remove.firstChapter||'';keep.discoveryPoint=keep.discoveryPoint||remove.discoveryPoint||'';keep.sessionId=keep.sessionId||remove.sessionId||'';
 const replaceId=id=>id===removeId?keepId:id;
 const merged=[];
 b.relationships.forEach(r=>{
   r.from=replaceId(r.from);r.to=replaceId(r.to);
   if(r.from===r.to)return;
   const existing=merged.find(x=>x.from===r.from&&x.to===r.to);
   if(!existing){merged.push(r);return}
   const labels=new Map((existing.items||[]).map(i=>[normalizeRelationText(i.label),i]));
   (r.items||[]).forEach(i=>{const k=normalizeRelationText(i.label);if(!labels.has(k)){existing.items.push(i);existing.types=existing.items.map(x=>x.label)} });
   const chNums=[existing.chapter,r.chapter].map(v=>parseInt(v,10)).filter(Number.isFinite);if(chNums.length)existing.chapter=String(Math.min(...chNums));
   if(!existing.discoveryPoint&&r.discoveryPoint)existing.discoveryPoint=r.discoveryPoint;
   if(!existing.sessionId&&r.sessionId)existing.sessionId=r.sessionId;
 });
 b.relationships=merged;
 b.sessions.forEach(s=>{s.characterIds=[...new Set((s.characterIds||[]).map(replaceId).filter(Boolean))];});
 b.characters=b.characters.filter(c=>c.id!==removeId);
 if(mapState.focus===removeId)mapState.focus=keepId;if(mapState.networkSelected===removeId)mapState.networkSelected=keepId;
 save();close();renderCharacters();toast(`${keep.name} quedó como personaje conservado`);
}

// --- Relationships ---------------------------------------------------------
function relLabels(r){return (r.items||[]).map(it=>esc(it.label)).join(' · ')}
function relationshipRow(b,r){const a=b.characters.find(c=>c.id===r.from),z=b.characters.find(c=>c.id===r.to);const hasSym=(r.items||[]).some(it=>it.mode==='symmetric');const hasDir=(r.items||[]).some(it=>it.mode==='directed');const dir=hasSym&&!hasDir?'↔':'→';return `<div class="relationship"><span class="node">${esc(a?.name||'?')}</span><span class="arrow">— ${relLabels(r)} ${dir}</span><span class="node">${esc(z?.name||'?')}</span><div class="rel-actions"><button class="secondary" onclick="editRelationship('${r.id}')">Editar</button><button class="danger" onclick="deleteRelationship('${r.id}')">Eliminar</button></div></div>`}
const relCheckboxes=(selected=[])=>relTypes.map(x=>`<label class="check-option"><input type="checkbox" name="types" value="${esc(x)}" ${selected.includes(x)?'checked':''}> <span>${esc(x)}</span></label>`).join('');
function relationshipForm(title,rel){const b=active(),r=rel||{from:b.characters[0]?.id||'',to:b.characters[1]?.id||'',items:[],chapter:''};const selected=(r.items||[]).map(i=>i.label);const custom=selected.find(x=>!REL_CATALOG[x]);return `<h2>${title}</h2><form onsubmit="${rel?'updateRelationship(event,\''+rel.id+'\')':'createRelationship(event)'}"><div class="grid"><div class="field"><label>Personaje A</label><select name="from">${b.characters.map(c=>`<option value="${c.id}" ${c.id===r.from?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Personaje B</label><select name="to">${b.characters.map(c=>`<option value="${c.id}" ${c.id===r.to?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div></div><div class="field"><label>Relaciones <span class="muted">(puedes elegir varias)</span></label><div class="check-grid">${relCheckboxes(selected.filter(x=>REL_CATALOG[x]))}</div></div><div class="field"><label>Otra relación personalizada <span class="muted">(opcional)</span></label><input name="custom" value="${esc(custom||'')}" placeholder="Ej.: protector, rival literario, cliente..."></div><div class="grid"><div class="field"><label>Dirección de la relación personalizada</label><select name="customMode"><option value="directed">A → B (direccional)</option><option value="symmetric" ${r.items?.find(i=>i.label===custom)?.mode==='symmetric'?'selected':''}>A ↔ B (mutua)</option></select></div><div class="field"><label>Desde qué capítulo es válida</label><input name="chapter" type="number" min="0" value="${esc(r.chapter||'')}"></div></div><div class="field"><label>Punto de descubrimiento <span class="muted">(opcional)</span></label><input name="discoveryPoint" value="${esc(r.discoveryPoint||'')}"></div><div class="hint">Las relaciones estándar ya tienen una dirección definida. Por ejemplo, “jefe de” apunta de A hacia B, mientras “colega de” es mutua.</div><button class="primary">Guardar relación</button></form>`}
function newRelationship(){const b=active();if(b.characters.length<2){modal('<h2>Primero añade personajes</h2><p class="muted">Necesitas al menos dos personajes para crear una relación.</p>');return}modal(relationshipForm('Nueva relación'))}
function getRelationshipData(f){const labels=f.getAll('types');const custom=String(f.get('custom')||'').trim();if(custom)labels.push(custom);const unique=[...new Set(labels.length?labels:['otra relación'])];const customMode=f.get('customMode')||'directed',customCategory=f.get('customCategory')||'Otra';const items=unique.map(label=>({label,mode:label===custom?customMode:inferRel(label).mode,category:label===custom?customCategory:inferRel(label).category}));return {from:f.get('from'),to:f.get('to'),items,types:items.map(i=>i.label),chapter:f.get('chapter')||'',discoveryPoint:f.get('discoveryPoint')||''}}
function createRelationship(e){e.preventDefault();const f=new FormData(e.target),data=getRelationshipData(f);if(data.from===data.to){modal('<h2>Relación no válida</h2><p class="muted">Un personaje no puede relacionarse consigo mismo.</p>');return}active().relationships.push({id:uid(),...data});save();close();renderCharacters();toast('Conexión creada')}
function editRelationship(id){const r=active().relationships.find(x=>x.id===id);if(!r)return;modal(relationshipForm('Editar relación',r))}
function updateRelationship(e,id){e.preventDefault();const f=new FormData(e.target),data=getRelationshipData(f);if(data.from===data.to){modal('<h2>Relación no válida</h2><p class="muted">Un personaje no puede relacionarse consigo mismo.</p>');return}const r=active().relationships.find(x=>x.id===id);if(!r)return;Object.assign(r,data);save();close();renderCharacters();toast('Conexión actualizada')}
function deleteRelationship(id){active().relationships=active().relationships.filter(r=>r.id!==id);save();renderCharacters();toast('Conexión eliminada')}

// --- Map -------------------------------------------------------------------
let mapState={focus:null,level:'direct',scope:'current',categories:new Set(Object.values(REL_CATALOG).map(x=>x.category)),zoom:1,panX:0,panY:0,viewMode:'focus',networkSelected:null,networkPositions:{}};
function chapterNum(v){const n=parseInt(v,10);return Number.isFinite(n)?n:Infinity}
function hasKnownChapter(v){return Number.isFinite(parseInt(v,10))}
function currentChapter(){const b=active();const last=b?.sessions?.at(-1);return last?chapterNum(last.chapter):Infinity}
function relVisible(r){const cats=(r.items||[]).map(i=>i.category);return cats.some(c=>mapState.categories.has(c))}
function mapFilterData(b){
 let chars=[...(b.characters||[])],rels=[...(b.relationships||[])];
 // Apply anti-spoiler and category filters before building the visible network.
 if(mapState.scope==='current'){const cur=currentChapter();if(cur!==Infinity){chars=chars.filter(c=>chapterNum(c.firstChapter)<=cur);rels=rels.filter(r=>!hasKnownChapter(r.chapter)||chapterNum(r.chapter)<=cur)}}
 rels=rels.filter(relVisible);const availableIds=new Set(chars.map(c=>c.id));rels=rels.filter(r=>availableIds.has(r.from)&&availableIds.has(r.to));
 if(!mapState.focus)return {chars,rels};

 // First hop: central character plus every directly connected character.
 const directIds=new Set([mapState.focus]);
 rels.forEach(r=>{if(r.from===mapState.focus)directIds.add(r.to);if(r.to===mapState.focus)directIds.add(r.from)});

 if(mapState.level==='direct'){
  const visibleRelationships=rels.filter(r=>directIds.has(r.from)&&directIds.has(r.to));
  return {chars:chars.filter(c=>directIds.has(c.id)),rels:visibleRelationships};
 }

 if(mapState.level==='2'){
  // Second hop is non-directed for discovery. Keep the full induced subgraph
  // afterwards, so links between secondary characters remain visible.
  const twoHopIds=new Set(directIds);
  rels.forEach(r=>{if(directIds.has(r.from))twoHopIds.add(r.to);if(directIds.has(r.to))twoHopIds.add(r.from)});
  const visibleRelationships=rels.filter(r=>twoHopIds.has(r.from)&&twoHopIds.has(r.to));
  return {chars:chars.filter(c=>twoHopIds.has(c.id)),rels:visibleRelationships};
 }

 return {chars,rels};
}
function colorForCategory(cat){return ({'Familia':'#2f855a','Amistad':'#3578c8','Trabajo':'#b7791f','Académica / Mentoría':'#7b5cc7','Romance':'#c05687','Conflicto':'#d04444','Otra':'#6b7280'})[cat]||'#6b7280'}
function truncateLabel(text,max=18){if(text.length<=max)return text;const parts=text.split(/\s+/);if(parts.length>1){let out='';for(const p of parts){if((out+' '+p).trim().length>max)break;out=(out+' '+p).trim()}if(out.length>=8)return out+'…'}return text.slice(0,max-1)+'…'}
function layoutGraph(chars,rels,W,H){
 const center={x:W/2,y:H/2};const positions={};const focus=mapState.focus&&chars.some(c=>c.id===mapState.focus)?mapState.focus:(chars[0]?.id||null);
 const centerId=focus;
 positions[centerId]={x:center.x,y:center.y};
 const neighbors=new Set();rels.forEach(r=>{if(r.from===centerId)neighbors.add(r.to);if(r.to===centerId)neighbors.add(r.from)});
 const first=chars.filter(c=>c.id!==centerId&&neighbors.has(c.id));const rest=chars.filter(c=>c.id!==centerId&&!neighbors.has(c.id));
 const placeRing=(list,radius,offset)=>list.forEach((c,i)=>{const a=offset+(2*Math.PI*i/Math.max(list.length,1));positions[c.id]={x:center.x+radius*Math.cos(a),y:center.y+radius*Math.sin(a)}});
 const innerRadius=Math.min(W,H)*.28,outerRadius=Math.min(W,H)*.42;
 // Two direct neighbours on opposite sides of a full ring create a vertical
 // chain. Fan them out below the central node so their own link stays visible
 // as the base of a triangle; larger groups remain radial around the centre.
 if(first.length===1)placeRing(first,innerRadius,-Math.PI/2);
 else if(first.length===2){const angles=[3*Math.PI/4,Math.PI/4];first.forEach((c,i)=>{const a=angles[i];positions[c.id]={x:center.x+innerRadius*Math.cos(a),y:center.y+innerRadius*Math.sin(a)}})}
 else placeRing(first,innerRadius,-Math.PI/2);
 // Nodes reached only through a direct neighbour occupy an outer layer.
 placeRing(rest,outerRadius,-Math.PI/2+0.2);
 // Lightweight collision relaxation for many nodes.
 for(let iter=0;iter<30;iter++){for(const a of chars){if(a.id===centerId)continue;for(const z of chars){if(a.id>=z.id||z.id===centerId)continue;const p=positions[a.id],q=positions[z.id];if(!p||!q)continue;let dx=p.x-q.x,dy=p.y-q.y,d=Math.hypot(dx,dy)||1;const min=108;if(d<min){const push=(min-d)/2,ux=dx/d,uy=dy/d;p.x+=ux*push;p.y+=uy*push;q.x-=ux*push;q.y-=uy*push}}pClamp(positions[a.id],W,H)}}
 return positions;
}
function pClamp(p,W,H){p.x=Math.max(70,Math.min(W-70,p.x));p.y=Math.max(70,Math.min(H-70,p.y))}
function edgeGeometry(a,z,radA=45,radZ=45,curve=0){const dx=z.x-a.x,dy=z.y-a.y,len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len;return {sx:a.x+ux*radA,sy:a.y+uy*radA,ex:z.x-ux*radZ,ey:z.y-uy*radZ,dx,dy,len,ux,uy,mx:(a.x+z.x)/2+(-uy)*curve,my:(a.y+z.y)/2+(ux)*curve}}
function renderMap(){if(!requireBook())return;const b=active(),allChars=b.characters||[];if(allChars.length<2){document.getElementById('app').innerHTML=`<div class="section-title"><div><h2>🕸️ Mapa de personajes</h2><div class="muted">${esc(b.title)}</div></div></div><div class="card hero"><h3>Aún no hay suficientes personajes</h3><p class="muted">Registra al menos dos personajes para construir el mapa de conexiones.</p><button class="primary" onclick="view('characters')">Ir a personajes</button></div>`;return}
 if(!mapState.focus||!allChars.some(c=>c.id===mapState.focus))mapState.focus=allChars[0].id;
 const filtered=mapFilterData(b),chars=filtered.chars,rels=filtered.rels;
 const focusName=allChars.find(c=>c.id===mapState.focus)?.name||'Personaje';
 const cats=['Familia','Amistad','Trabajo','Académica / Mentoría','Romance','Conflicto','Otra'];
 const cur=currentChapter();
 const app=document.getElementById('app');
 const focusToolbar=`<label>Personaje seleccionado</label><select id="mapFocus" onchange="setMapFocus(this.value)">${allChars.map(c=>`<option value="${c.id}" ${c.id===mapState.focus?'selected':''}>${esc(c.name)}</option>`).join('')}</select><label>Nivel</label><div class="seg"><button class="${mapState.level==='direct'?'active':''}" onclick="setMapLevel('direct')">Directos</button><button class="${mapState.level==='2'?'active':''}" onclick="setMapLevel('2')">2 niveles</button><button class="${mapState.level==='all'?'active':''}" onclick="setMapLevel('all')">Todos</button></div>`;
 const networkToolbar=`<span class="network-mode-note">Cada conexión atrae; los nodos se separan automáticamente.</span><button onclick="reorganizeNetwork()">⟳ Reorganizar red</button>`;
 app.innerHTML=`<div class="section-title"><div><h2>🕸️ Mapa de personajes</h2><div class="muted">${esc(b.title)} · ${chars.length} personajes visibles · ${rels.length} conexiones visibles · ${b.relationships.length} conexiones en total</div></div><div class="actions"><button class="secondary" onclick="resetMapView()">↺ Reiniciar vista</button><button class="secondary" onclick="view('characters')">Editar relaciones</button></div></div>
 <div class="map-shell">
  <div class="card map-card">
   <div class="map-toolbar"><label>Vista</label><div class="seg"><button class="${mapState.viewMode==='focus'?'active':''}" onclick="setMapViewMode('focus')">🎯 Enfoque</button><button class="${mapState.viewMode==='network'?'active':''}" onclick="setMapViewMode('network')">🕸️ Red</button></div>${mapState.viewMode==='focus'?focusToolbar:networkToolbar}<label>Diseño</label><button onclick="recenterMap()">Ajustar vista</button></div>
   <div class="map-wrap" id="mapWrap"><div class="zoom-box"><button onclick="mapZoom(-.15)">−</button><button onclick="mapZoom(0)">${Math.round(mapState.zoom*100)}%</button><button onclick="mapZoom(.15)">+</button></div><svg id="mapSvg" viewBox="0 0 1000 680" role="img" aria-label="Mapa de relaciones entre personajes"></svg><div id="mapTooltip" class="map-tooltip hidden"></div></div>
  </div>
  <aside class="map-side">
   <div class="card filter-card"><h3>👁️ Mostrar personajes</h3><div class="radio-list"><label><input type="radio" name="scope" value="current" ${mapState.scope==='current'?'checked':''} onchange="setMapScope(this.value)"> Hasta el capítulo actual${cur!==Infinity?` (${cur})`:''}</label><label><input type="radio" name="scope" value="all" ${mapState.scope==='all'?'checked':''} onchange="setMapScope(this.value)"> Todos los personajes</label></div><div class="focus-note">${mapState.scope==='current'&&cur===Infinity?'Aún no hay una sesión con capítulo registrado. Se muestran todos los datos.':''}</div></div>
   <div class="card filter-card"><h3>🔎 Filtros de relaciones</h3><div class="filter-list">${cats.map(cat=>`<label><input type="checkbox" ${mapState.categories.has(cat)?'checked':''} onchange="toggleMapCategory('${cat}',this.checked)"><span style="width:9px;height:9px;border-radius:50%;background:${colorForCategory(cat)};display:inline-block"></span>${esc(cat)}</label>`).join('')}</div></div>
   <div class="card filter-card"><h3>${mapState.viewMode==='focus'?'📌 Personaje central':'🕸️ Vista de red'}</h3>${mapState.viewMode==='focus'?`<strong>${esc(focusName)}</strong><div class="focus-note">${mapState.level==='direct'?'Solo conexiones directas':mapState.level==='2'?'Hasta dos niveles de distancia':'Red completa visible'}</div>`:`<div class="focus-note">No hay personaje central. La posición se calcula automáticamente según las conexiones.</div>`}</div>
   <div class="card"><h3>📖 Cómo leer el mapa</h3><div class="map-help"><strong>A → B</strong> significa que A tiene esa relación hacia B.<br><strong>A ↔ B</strong> significa que la relación es mutua.<br><br>Los nombres largos se resumen dentro del círculo. <strong>Pasa el mouse</strong> sobre el nodo para ver el nombre completo y la descripción.${mapState.viewMode==='network'?'<br><br><strong>🕸️ Vista de red:</strong> los personajes se organizan automáticamente según sus conexiones. Puedes arrastrarlos para explorar la red.':''}</div><div class="legend-row"><span class="legend-arrow">→</span> Relación direccional</div><div class="legend-row"><span class="legend-arrow">↔</span> Relación mutua</div></div>
  </aside>
 </div>
 <div class="card table-card"><div class="section-title"><div><h3>🔗 Conexiones registradas</h3><div class="muted">${b.relationships.length} conexiones en total</div></div><div class="actions"><button class="secondary" onclick="relationshipDiagnostics()">Diagnóstico</button><button class="secondary" onclick="newRelationship()">+ Nueva relación</button></div></div><div class="map-table"><table><thead><tr><th>Personaje A</th><th>Relaciones</th><th>Dirección</th><th>Personaje B</th><th>Descubierto</th><th>Acciones</th></tr></thead><tbody>${b.relationships.length?b.relationships.map(r=>{const a=b.characters.find(c=>c.id===r.from),z=b.characters.find(c=>c.id===r.to);const sym=(r.items||[]).some(i=>i.mode==='symmetric'),dir=(r.items||[]).some(i=>i.mode==='directed');const arrow=sym&&!dir?'↔':'→';return `<tr><td>${esc(a?.name||'?')}</td><td>${(r.items||[]).map(i=>`<span class="relation-pill">${esc(i.label)}</span>`).join('')}</td><td class="relation-dir">${arrow}</td><td>${esc(z?.name||'?')}</td><td>Cap. ${esc(r.chapter||'?')}</td><td><button class="icon-btn" onclick="editRelationship('${r.id}')">✎</button> <button class="icon-btn" onclick="deleteRelationship('${r.id}')">🗑</button></td></tr>`}).join(''):`<tr><td colspan="6" class="muted">Todavía no hay conexiones.</td></tr>`}</tbody></table></div></div>`;
 drawMap(filtered.chars,filtered.rels);
}
function createArrowMarker(defs,id){const mk=document.createElementNS('http://www.w3.org/2000/svg','marker');mk.setAttribute('id',id);mk.setAttribute('viewBox','0 0 10 10');mk.setAttribute('refX','8');mk.setAttribute('refY','5');mk.setAttribute('markerWidth','7');mk.setAttribute('markerHeight','7');mk.setAttribute('orient','auto');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M 0 0 L 10 5 L 0 10 z');path.setAttribute('fill','#687080');mk.appendChild(path);defs.appendChild(mk)}
function drawMap(chars,rels){const svg=document.getElementById('mapSvg'),wrap=document.getElementById('mapWrap');if(!svg||!wrap)return;const W=1000,H=680;svg.innerHTML='';const defs=document.createElementNS('http://www.w3.org/2000/svg','defs');createArrowMarker(defs,'arrowHead');svg.appendChild(defs);if(mapState.viewMode==='network')drawNetworkMap(svg,wrap,chars,rels,W,H);else drawFocusMap(svg,wrap,chars,rels,W,H)}
function drawFocusMap(svg,wrap,chars,rels,W,H){const pos=layoutGraph(chars,rels,W,H);const edgeLayer=document.createElementNS('http://www.w3.org/2000/svg','g'),nodeLayer=document.createElementNS('http://www.w3.org/2000/svg','g');svg.appendChild(edgeLayer);svg.appendChild(nodeLayer);const pairCounts={};rels.forEach(r=>{const key=[r.from,r.to].sort().join('|');pairCounts[key]=(pairCounts[key]||0)+1});const pairIndexes={};rels.forEach(r=>{const a=pos[r.from],z=pos[r.to];if(!a||!z)return;const items=r.items||[];const key=[r.from,r.to].sort().join('|');const idx=pairIndexes[key]||0;pairIndexes[key]=idx+1;const curve=((idx%2===0)?1:-1)*Math.min(35,10+((pairCounts[key]-1)*8));const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','map-edge');const geom=edgeGeometry(a,z,47,47,curve);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',geom.sx);line.setAttribute('y1',geom.sy);line.setAttribute('x2',geom.ex);line.setAttribute('y2',geom.ey);const hasDir=items.some(x=>x.mode==='directed'),hasSym=items.some(x=>x.mode==='symmetric');if(hasDir&&!hasSym)line.setAttribute('marker-end','url(#arrowHead)');if(hasSym&&!hasDir){line.setAttribute('marker-start','url(#arrowHead)');line.setAttribute('marker-end','url(#arrowHead)')}line.style.stroke=colorForCategory(items[0]?.category);g.appendChild(line);const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('x',geom.mx);label.setAttribute('y',geom.my);label.setAttribute('text-anchor','middle');label.textContent=items.map(x=>x.label).join(' · ')+(hasKnownChapter(r.chapter)?'':' · Cap. ?');g.appendChild(label);edgeLayer.appendChild(g)});drawMapNodes(nodeLayer,chars,rels,pos,false);setupMapPointer(wrap,svg)}
function nodeRadius(c,rels){const degree=new Set();rels.forEach(r=>{if(r.from===c.id)degree.add(r.to);if(r.to===c.id)degree.add(r.from)});return Math.max(38,Math.min(52,39+degree.size*2))}
function drawMapNodes(nodeLayer,chars,rels,pos,network){chars.forEach(c=>{const p=pos[c.id];if(!p)return;const g=document.createElementNS('http://www.w3.org/2000/svg','g');const selected=network?mapState.networkSelected===c.id:mapState.focus===c.id;g.setAttribute('class','map-node'+(selected?' selected':''));g.setAttribute('transform',`translate(${p.x} ${p.y})`);g.dataset.id=c.id;const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('r',network?nodeRadius(c,rels):47);circle.style.stroke=colorForCategory((rels.find(r=>r.from===c.id||r.to===c.id)?.items?.[0]?.category)||'Otra');g.appendChild(circle);const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('class','node-title');label.setAttribute('text-anchor','middle');label.setAttribute('y',network?'4':(c.shortName||c.name.length<=20?'4':'-2'));const short=truncateLabel(displayName(c),18);label.textContent=short;g.appendChild(label);if(displayName(c)!==short){const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('text-anchor','middle');t.setAttribute('y','17');t.setAttribute('class','node-title');t.textContent='…';g.appendChild(t)}g.addEventListener('click',e=>{e.stopPropagation();if(network){selectNetworkNode(c.id)}else setMapFocus(c.id)});g.addEventListener('mouseenter',e=>showNodeTooltip(c,e));g.addEventListener('mouseleave',hideNodeTooltip);g.addEventListener('touchstart',e=>{e.stopPropagation();showNodeTooltip(c,e.touches[0]);setTimeout(hideNodeTooltip,3200)},{passive:true});nodeLayer.appendChild(g)})}
function drawNetworkMap(svg,wrap,chars,rels,W,H){
 const edgeLayer=document.createElementNS('http://www.w3.org/2000/svg','g'),nodeLayer=document.createElementNS('http://www.w3.org/2000/svg','g');
 svg.appendChild(edgeLayer);svg.appendChild(nodeLayer);
 const pos=forceLayout(chars,rels,W,H);
 const pairCounts={};rels.forEach(r=>{const key=[r.from,r.to].sort().join('|');pairCounts[key]=(pairCounts[key]||0)+1});
 const pairIndexes={};
 rels.forEach(r=>{
  const a=pos[r.from],z=pos[r.to];if(!a||!z)return;
  const items=r.items||[],key=[r.from,r.to].sort().join('|'),idx=pairIndexes[key]||0;pairIndexes[key]=idx+1;
  const curve=((idx%2===0)?1:-1)*Math.min(42,10+((pairCounts[key]-1)*9));
  const geom=edgeGeometry(a,z,44,44,curve);
  const g=document.createElementNS('http://www.w3.org/2000/svg','g');
  g.setAttribute('class','map-edge network-edge');g.dataset.from=r.from;g.dataset.to=r.to;g.dataset.relId=r.id;
  const line=document.createElementNS('http://www.w3.org/2000/svg','line');
  line.setAttribute('x1',geom.sx);line.setAttribute('y1',geom.sy);line.setAttribute('x2',geom.ex);line.setAttribute('y2',geom.ey);
  const hasDir=items.some(x=>x.mode==='directed'),hasSym=items.some(x=>x.mode==='symmetric');
  if(hasDir&&!hasSym)line.setAttribute('marker-end','url(#arrowHead)');
  if(hasSym&&!hasDir){line.setAttribute('marker-start','url(#arrowHead)');line.setAttribute('marker-end','url(#arrowHead)')}
  line.style.stroke=colorForCategory(items[0]?.category);g.appendChild(line);
  const hit=document.createElementNS('http://www.w3.org/2000/svg','line');
  hit.setAttribute('class','network-edge-hit');hit.setAttribute('x1',geom.sx);hit.setAttribute('y1',geom.sy);hit.setAttribute('x2',geom.ex);hit.setAttribute('y2',geom.ey);g.appendChild(hit);
  g.addEventListener('mouseenter',e=>showEdgeTooltip(r,e));
  g.addEventListener('mouseleave',hideNodeTooltip);
  g.addEventListener('click',e=>{e.stopPropagation();selectNetworkEdge(r.id)});
  g.addEventListener('touchstart',e=>{e.stopPropagation();showEdgeTooltip(r,e.touches[0]);setTimeout(hideNodeTooltip,3200)},{passive:true});
  edgeLayer.appendChild(g);
 });
 drawMapNodes(nodeLayer,chars,rels,pos,true);
 setupNetworkInteractions(wrap,svg,chars,rels,pos,edgeLayer,nodeLayer);
}
function seedNetworkPositions(chars,W,H){const out={...mapState.networkPositions};chars.forEach((c,i)=>{if(!out[c.id]){const a=(2*Math.PI*i/Math.max(chars.length,1));out[c.id]={x:W/2+Math.cos(a)*Math.min(W,H)*.28,y:H/2+Math.sin(a)*Math.min(W,H)*.28}}});mapState.networkPositions=out;return out}
function forceLayout(chars,rels,W,H){const pos=seedNetworkPositions(chars,W,H);const nodes=chars.map(c=>({id:c.id,x:pos[c.id].x,y:pos[c.id].y,vx:0,vy:0}));const byId=new Map(nodes.map(n=>[n.id,n]));const links=[];rels.forEach(r=>{const a=byId.get(r.from),b=byId.get(r.to);if(a&&b)links.push([a,b])});const n=Math.max(nodes.length,1);for(let iter=0;iter<180;iter++){const alpha=0.9*(1-iter/180)+0.08;for(const a of nodes){for(const b of nodes){if(a===b)continue;let dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy)||1;const min=120;const force=(min*min)/(d*d)*0.55*alpha;const ux=dx/d,uy=dy/d;a.vx+=ux*force;a.vy+=uy*force}a.vx+=(W/2-a.x)*0.0015*alpha;a.vy+=(H/2-a.y)*0.0015*alpha}for(const [a,b] of links){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;const target=150;const force=(d-target)*0.012*alpha;const ux=dx/d,uy=dy/d;a.vx+=ux*force;a.vy+=uy*force;b.vx-=ux*force;b.vy-=uy*force}for(const a of nodes){a.vx*=0.82;a.vy*=0.82;a.x+=a.vx;a.y+=a.vy;a.x=Math.max(65,Math.min(W-65,a.x));a.y=Math.max(65,Math.min(H-65,a.y))}}
 const result={};nodes.forEach(n=>{result[n.id]={x:n.x,y:n.y};mapState.networkPositions[n.id]={x:n.x,y:n.y}});return result}
function selectNetworkNode(id){mapState.networkSelected=mapState.networkSelected===id?null:id;updateNetworkHighlight()}
function updateNetworkHighlight(){const svg=document.getElementById('mapSvg');if(!svg)return;const selected=mapState.networkSelected;const b=active();const filtered=mapFilterData(b);const connected=new Set();if(selected){filtered.rels.forEach(r=>{if(r.from===selected)connected.add(r.to);if(r.to===selected)connected.add(r.from)})}svg.querySelectorAll('.map-node').forEach(g=>{const id=g.dataset.id;g.classList.toggle('network-dimmed',!!selected&&id!==selected&&!connected.has(id));g.classList.toggle('selected',id===selected)});svg.querySelectorAll('.network-edge').forEach(g=>{const hit=!!selected&&(g.dataset.from===selected||g.dataset.to===selected);g.classList.toggle('network-edge-dimmed',!!selected&&!hit);g.classList.toggle('network-edge-active',hit)});applyNetworkEdgeLabelVisibility(filtered.rels)}
function setupNetworkInteractions(wrap,svg,chars,rels,pos,edgeLayer,nodeLayer){let dragging=null,last=null;nodeLayer.querySelectorAll('.map-node').forEach(g=>{g.addEventListener('pointerdown',e=>{dragging=g.dataset.id;last={x:e.clientX,y:e.clientY};g.setPointerCapture?.(e.pointerId);g.classList.add('dragging-node');e.stopPropagation()});g.addEventListener('pointermove',e=>{if(!dragging||dragging!==g.dataset.id)return;const rect=wrap.getBoundingClientRect();const sx=1000/rect.width,sy=680/rect.height;const p=pos[dragging];p.x=Math.max(60,Math.min(940,p.x+(e.clientX-last.x)*sx));p.y=Math.max(60,Math.min(620,p.y+(e.clientY-last.y)*sy));last={x:e.clientX,y:e.clientY};mapState.networkPositions[dragging]={x:p.x,y:p.y};g.setAttribute('transform',`translate(${p.x} ${p.y})`);updateNetworkEdges(svg,rels,pos)});g.addEventListener('pointerup',()=>{dragging=null;g.classList.remove('dragging-node')});g.addEventListener('pointercancel',()=>{dragging=null;g.classList.remove('dragging-node')})});svg.addEventListener('click',e=>{if(e.target===svg){mapState.networkSelected=null;updateNetworkHighlight()}});updateNetworkHighlight()}
function updateNetworkEdges(svg,rels,pos){const groups=[...svg.querySelectorAll('.network-edge')];const pairCounts={};rels.forEach(r=>{const key=[r.from,r.to].sort().join('|');pairCounts[key]=(pairCounts[key]||0)+1});const pairIndexes={};groups.forEach(g=>{const from=g.dataset.from,to=g.dataset.to,r=rels.find(x=>x.id===g.dataset.relId)||rels.find(x=>x.from===from&&x.to===to);if(!r)return;const a=pos[from],z=pos[to],key=[from,to].sort().join('|'),idx=pairIndexes[key]||0;pairIndexes[key]=idx+1;const curve=((idx%2===0)?1:-1)*Math.min(42,10+((pairCounts[key]-1)*9));const geom=edgeGeometry(a,z,44,44,curve);const lines=g.querySelectorAll('line');const line=lines[0],hitLine=lines[1];if(line){line.setAttribute('x1',geom.sx);line.setAttribute('y1',geom.sy);line.setAttribute('x2',geom.ex);line.setAttribute('y2',geom.ey)}if(hitLine){hitLine.setAttribute('x1',geom.sx);hitLine.setAttribute('y1',geom.sy);hitLine.setAttribute('x2',geom.ex);hitLine.setAttribute('y2',geom.ey)}const label=g.querySelector('text');if(label){label.setAttribute('x',geom.mx);label.setAttribute('y',geom.my)}});}
function networkRelationText(r){return (r.items||[]).map(i=>i.label).join(' · ')||'otra relación'}
function relationDirectionText(r){const hasSym=(r.items||[]).some(i=>i.mode==='symmetric'),hasDir=(r.items||[]).some(i=>i.mode==='directed');return hasSym&&!hasDir?'↔':'→'}
function showEdgeTooltip(r,e){const tip=document.getElementById('mapTooltip'),wrap=document.getElementById('mapWrap'),b=active();if(!tip||!wrap)return;const a=b.characters.find(c=>c.id===r.from),z=b.characters.find(c=>c.id===r.to);if(!a||!z)return;const direction=relationDirectionText(r),chapter=hasKnownChapter(r.chapter)?`Capítulo ${esc(r.chapter)}`:'Capítulo desconocido';tip.innerHTML=`<strong>${esc(a.name)} ${direction} ${esc(z.name)}</strong><div>${esc(networkRelationText(r))}</div><div style="opacity:.75;margin-top:4px">Descubierto: ${chapter}</div>${r.sessionId?'<div style="opacity:.75">Asociado a una sesión de lectura</div>':''}`;tip.classList.remove('hidden');const rect=wrap.getBoundingClientRect();let x=(e.clientX||rect.left+20)-rect.left+14,y=(e.clientY||rect.top+20)-rect.top+14;x=Math.max(8,Math.min(rect.width-258,x));y=Math.max(8,Math.min(rect.height-105,y));tip.style.left=x+'px';tip.style.top=y+'px'}
function selectNetworkEdge(id){const b=active(),r=b.relationships.find(x=>x.id===id);if(!r)return;const a=b.characters.find(c=>c.id===r.from),z=b.characters.find(c=>c.id===r.to);const direction=relationDirectionText(r),chapter=hasKnownChapter(r.chapter)?`Capítulo ${esc(r.chapter)}`:'Capítulo desconocido';modal(`<h2>🔗 Conexión</h2><div class="relationship"><span class="node">${esc(a?.name||'?')}</span><span class="arrow">— ${esc(networkRelationText(r))} ${direction}</span><span class="node">${esc(z?.name||'?')}</span></div><p class="muted">Descubierto: ${chapter}</p>${r.sessionId?`<p class="muted">Esta relación está asociada a una sesión de lectura.</p>`:''}<div class="actions"><button class="primary" onclick="editRelationship('${r.id}')">Editar relación</button>${r.sessionId?`<button class="secondary" onclick="viewSession('${r.sessionId}')">Ver sesión</button>`:''}</div>`)}
function showNodeTooltip(c,e){const tip=document.getElementById('mapTooltip'),wrap=document.getElementById('mapWrap');if(!tip||!wrap)return;let extra='';if(mapState.viewMode==='network'){const b=active(),rels=(b.relationships||[]).filter(r=>r.from===c.id||r.to===c.id),neighbors=new Set();rels.forEach(r=>{neighbors.add(r.from===c.id?r.to:r.from)});extra=`<div style="margin-top:5px">${neighbors.size} conexión${neighbors.size===1?'':'es'} · ${rels.length} relación${rels.length===1?'':'es'}</div>`}tip.innerHTML=`<strong>${esc(c.name)}</strong>${c.description?`<div>${esc(c.description)}</div>`:''}<div style="opacity:.75;margin-top:4px">Descubierto en capítulo ${esc(c.firstChapter||'?')}</div>${extra}`;tip.classList.remove('hidden');const r=wrap.getBoundingClientRect();let x=(e.clientX||r.left+20)-r.left+14,y=(e.clientY||r.top+20)-r.top+14;x=Math.max(8,Math.min(r.width-258,x));y=Math.max(8,Math.min(r.height-110,y));tip.style.left=x+'px';tip.style.top=y+'px'}
function hideNodeTooltip(){document.getElementById('mapTooltip')?.classList.add('hidden')}
function setMapViewMode(mode){mapState.viewMode=mode;mapState.networkSelected=null;renderMap()}
function setMapFocus(id){mapState.focus=id;renderMap()}
function setMapLevel(level){mapState.level=level;renderMap()}
function reorganizeNetwork(){mapState.networkPositions={};mapState.panX=0;mapState.panY=0;if(mapState.viewMode==='network')renderMap();else toast('Cambia a Vista de red para reorganizarla')}
function setMapScope(scope){mapState.scope=scope;renderMap()}
function toggleMapCategory(cat,on){if(on)mapState.categories.add(cat);else mapState.categories.delete(cat);renderMap()}
function resetMapView(){mapState.level='direct';mapState.scope='current';mapState.zoom=1;mapState.panX=0;mapState.panY=0;mapState.networkSelected=null;renderMap()}
function recenterMap(){mapState.panX=0;mapState.panY=0;mapState.zoom=1;renderMap()}
function mapZoom(delta){mapState.zoom=Math.max(.6,Math.min(1.7,mapState.zoom+(delta||0)));const svg=document.getElementById('mapSvg');if(svg)svg.style.transform=`scale(${mapState.zoom})`;if(delta===0)toast(Math.round(mapState.zoom*100)+'%')}
function setupMapPointer(wrap,svg){let dragging=false,last=null;wrap.onpointerdown=e=>{if(e.target.closest('.map-node')||e.target.closest('.zoom-box'))return;dragging=true;last={x:e.clientX,y:e.clientY};svg.classList.add('dragging');wrap.setPointerCapture?.(e.pointerId)};wrap.onpointermove=e=>{if(!dragging)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;last={x:e.clientX,y:e.clientY};mapState.panX+=dx;mapState.panY+=dy;svg.style.transform=`translate(${mapState.panX}px,${mapState.panY}px) scale(${mapState.zoom})`};wrap.onpointerup=wrap.onpointercancel=()=>{dragging=false;svg.classList.remove('dragging')};svg.style.transform=`translate(${mapState.panX}px,${mapState.panY}px) scale(${mapState.zoom})`}

// --- Quotes ----------------------------------------------------------------
function renderQuotes(){if(!requireBook())return;const b=active();document.getElementById('app').innerHTML=`<div class="section-title"><div><h2>💬 Fragmentos</h2><div class="muted">Frases, párrafos e ideas que quieres conservar.</div></div><button class="primary" onclick="newQuote()">+ Fragmento</button></div>${b.quotes.length?`<div class="list">${b.quotes.slice().reverse().map(q=>`<div class="card"><div class="quote">${esc(q.text)}</div><div class="muted">Capítulo ${esc(q.chapter||'?')} · página ${esc(q.page||'?')} · ${esc(q.reason||'Sin categoría')}</div>${q.note?`<p><strong>Tu nota:</strong> ${esc(q.note)}</p>`:''}<button class="danger" onclick="deleteQuote('${q.id}')">Eliminar</button></div>`).join('')}`:`<div class="empty">Todavía no has guardado ningún fragmento.</div>`}`}
function newQuote(){modal(`<h2>Guardar fragmento</h2><form onsubmit="createQuote(event)"><div class="field"><label>Frase o párrafo</label><textarea name="text" required></textarea></div><div class="grid"><div class="field"><label>Capítulo</label><input name="chapter" type="number" min="0"></div><div class="field"><label>Página</label><input name="page" type="number" min="0"></div></div><div class="field"><label>¿Por qué lo guardas?</label><select name="reason"><option>Frase bonita</option><option>Idea interesante</option><option>Reflexión</option><option>Importante para la trama</option><option>Otro</option></select></div><div class="field"><label>Nota personal</label><textarea name="note"></textarea></div><button class="primary">Guardar fragmento</button></form>`)}
function createQuote(e){e.preventDefault();const f=new FormData(e.target);active().quotes.push({id:uid(),text:f.get('text'),chapter:f.get('chapter'),page:f.get('page'),reason:f.get('reason'),note:f.get('note')});save();close();renderQuotes()}
function deleteQuote(id){active().quotes=active().quotes.filter(q=>q.id!==id);save();renderQuotes()}

// --- Sessions and recap ----------------------------------------------------
function renderSessions(){if(!requireBook())return;const b=active();document.getElementById('app').innerHTML=`<div class="section-title"><div><h2>📍 Sesiones de lectura</h2><div class="muted">Registra exactamente dónde quedaste.</div></div><button class="primary" onclick="newSession()">+ Registrar lectura</button></div>${b.sessions.length?`<div class="list">${b.sessions.slice().reverse().map(s=>`<div class="card"><h3>Capítulo ${esc(s.chapter||'?')} · página ${esc(s.page||'?')}</h3><div class="muted">${esc(s.date)}</div>${s.summary?`<p><strong>Qué estaba pasando:</strong><br>${esc(s.summary)}</p>`:''}${s.note?`<p><strong>Mi impresión:</strong><br>${esc(s.note)}</p>`:''}</div>`).join('')}`:`<div class="empty">Aún no has registrado una sesión.</div>`}`}
function newSession(){modal(`<h2>Registrar lectura</h2><form onsubmit="createSession(event)"><div class="grid"><div class="field"><label>Capítulo</label><input name="chapter" type="number" min="0" required></div><div class="field"><label>Página</label><input name="page" type="number" min="0"></div></div><div class="field"><label>¿Qué estaba pasando?</label><textarea name="summary" placeholder="Escribe 1–3 frases para que puedas reconstruir el contexto."></textarea></div><div class="field"><label>Mi impresión</label><textarea name="note"></textarea></div><button class="primary">Guardar sesión</button></form>`)}
function createSession(e){e.preventDefault();const f=new FormData(e.target);active().sessions.push({id:uid(),date:new Date().toLocaleString('es-CR'),chapter:f.get('chapter'),page:f.get('page'),summary:f.get('summary'),note:f.get('note')});save();close();renderSessions();toast('Sesión guardada')}
function renderRecap(){if(!requireBook())return;const b=active(),last=b.sessions.at(-1),days=last?Math.max(0,Math.floor((Date.now()-new Date(last.date).getTime())/86400000)):null;const recent=last?`<div class="card hero"><h2>📍 Estabas aquí</h2><div class="stat">Cap. ${esc(last.chapter||'?')}</div><p>Página ${esc(last.page||'?')} · ${esc(last.date)}</p>${last.summary?`<p><strong>Qué estaba pasando:</strong><br>${esc(last.summary)}</p>`:''}${last.note?`<p><strong>Tu impresión:</strong><br>${esc(last.note)}</p>`:''}${days!==null&&days>7?`<div class="notice">Han pasado aproximadamente ${days} días desde tu última sesión. Este es un buen momento para hacer una puesta al día.</div>`:''}</div>`:`<div class="card hero"><h2>🧠 Tu punto de partida</h2><p>Aún no has registrado una sesión de lectura.</p><button class="primary" onclick="newSession()">Registrar dónde estoy</button></div>`;document.getElementById('app').innerHTML=`<div class="section-title"><div><h2>🧠 Retomar lectura</h2><div class="muted">${esc(b.title)} · ${esc(b.author||'')}</div></div><button class="secondary" onclick="editBook('${b.id}')">Editar libro</button></div>${recent}<div class="grid"><div class="card"><h3>👥 Personajes</h3><div class="stat">${b.characters.length}</div><div class="muted">registrados</div><button class="secondary" onclick="view('characters')">Ver personajes</button></div><div class="card"><h3>💬 Fragmentos</h3><div class="stat">${b.quotes.length}</div><div class="muted">guardados</div><button class="secondary" onclick="view('quotes')">Ver fragmentos</button></div><div class="card"><h3>📍 Sesiones</h3><div class="stat">${b.sessions.length}</div><div class="muted">registradas</div><button class="secondary" onclick="view('sessions')">Ver sesiones</button></div></div><div class="card"><h3>🔒 Modo anti-spoiler</h3><p class="muted">El mapa V5 puede mostrar solamente personajes y relaciones descubiertos hasta tu capítulo actual. Esto evita que una futura red de personajes te revele información que todavía no deberías conocer.</p><button class="secondary" onclick="view('map')">Abrir mapa</button></div>`}

// --- Reading sessions V5 ----------------------------------------------------
const SESSION_TYPES={chapter:'Capítulo',section:'Sección / parte',pages:'Páginas',since:'Desde mi última lectura',custom:'Personalizado'};
function sessionItems(b,ids,key){return (ids||[]).map(id=>(b[key]||[]).find(x=>x.id===id)).filter(Boolean)}
function sessionTypeFields(type,s={}){const last=active()?.sessions?.at(-1);if(type==='section')return `<div class="field"><label>Sección / parte</label><input name="section" value="${esc(s.section||'')}" required></div>`;if(type==='pages')return `<div class="grid"><div class="field"><label>Página inicial</label><input name="pageStart" type="number" min="0" value="${esc(s.pageStart||'')}" required></div><div class="field"><label>Página final</label><input name="pageEnd" type="number" min="0" value="${esc(s.pageEnd||'')}" required></div></div>`;if(type==='since')return `<div class="field"><label>Punto inicial</label><input name="lastPoint" value="${esc(s.pointStart||sessionPoint(last))}" readonly></div><div class="field"><label>Punto final</label><input name="pointEnd" value="${esc(s.pointEnd||'')}" required></div><input type="hidden" name="chapter" value="${esc(s.chapter||last?.chapter||'')}">`;if(type==='custom')return `<div class="field"><label>Punto de lectura</label><input name="pointEnd" value="${esc(s.pointEnd||'')}" required></div>`;return `<div class="grid"><div class="field"><label>Número o nombre del capítulo</label><input name="chapter" value="${esc(s.chapter||'')}" required></div><div class="field"><label>Página inicial</label><input name="pageStart" type="number" min="0" value="${esc(s.pageStart||'')}"></div><div class="field"><label>Página final</label><input name="pageEnd" type="number" min="0" value="${esc(s.pageEnd||s.page||'')}"></div></div>`}
function sessionChecks(name,items,selected,label,display){return `<div class="field"><label>${label}</label><div class="check-grid">${items.map(x=>`<label class="check-option"><input type="checkbox" name="${name}" value="${x.id}" ${(selected||[]).includes(x.id)?'checked':''}>${esc(display(x))}</label>`).join('')||'<span class="muted">No hay elementos registrados.</span>'}</div></div>`}
function sessionForm(title,s={}){const b=active(),type=s.sessionType||'chapter',id=s.id||uid();return `<h2>${title}</h2><form onsubmit="${s.id?`updateSession(event,'${s.id}')`:'createSession(event)'}"><input type="hidden" name="sessionId" value="${id}"><div class="field"><label>Tipo de sesión</label><select name="sessionType" onchange="updateSessionTypeFields(this.value)">${Object.entries(SESSION_TYPES).map(([k,v])=>`<option value="${k}" ${k===type?'selected':''}>${v}</option>`).join('')}</select></div><div id="sessionTypeFields">${sessionTypeFields(type,s)}</div><div class="grid"><div class="field"><label>Hora de inicio</label><input name="startedAt" type="time" value="${esc(s.startedAt||'')}"></div><div class="field"><label>Hora final</label><input name="endedAt" type="time" value="${esc(s.endedAt||'')}"></div><div class="field"><label>Duración (minutos)</label><input name="durationMinutes" type="number" min="0" value="${esc(s.durationMinutes||'')}"></div></div><div class="field"><label>📖 Trama — ¿Qué ocurrió?</label><textarea name="plot" placeholder="Acontecimientos de la novela">${esc(s.plot||s.summary||'')}</textarea></div>${sessionChecks('characterIds',b.characters,s.characterIds,'👥 Personajes relevantes',x=>x.name)}<div class="field"><label>Crear personaje desde esta sesión</label><input name="newCharacterName" placeholder="Nombre (opcional)"></div>${sessionChecks('relationshipIds',b.relationships,s.relationshipIds,'🔗 Relaciones descubiertas',x=>`${relLabels(x)}`)}<div class="grid"><select name="newRelFrom"><option value="">Crear relación: personaje A</option>${b.characters.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><select name="newRelTo"><option value="">Personaje B</option>${b.characters.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><select name="newRelType"><option value="">Tipo</option>${relTypes.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></div><div class="field"><label>📍 Lugares / contexto</label><textarea name="context" placeholder="Ej.: Can Gispert">${esc(s.context||'')}</textarea></div>${sessionChecks('quoteIds',b.quotes,s.quoteIds,'💬 Fragmentos',x=>x.text.slice(0,80))}<div class="field"><label>Crear fragmento desde esta sesión</label><textarea name="newQuoteText"></textarea></div><div class="field"><label>💭 Mi impresión</label><textarea name="impression" placeholder="Opiniones, hipótesis o impresiones">${esc(s.impression||s.note||'')}</textarea></div><button class="primary">Guardar sesión</button></form>`}
function updateSessionTypeFields(type){const el=document.getElementById('sessionTypeFields');if(el)el.innerHTML=sessionTypeFields(type)}
function sessionData(f){const type=f.get('sessionType'),chapter=f.get('chapter')||'',a=f.get('pageStart')||'',z=f.get('pageEnd')||'';let pointStart='',pointEnd=f.get('pointEnd')||'';if(type==='chapter'){pointStart=`Capítulo ${chapter}${a?` · pág. ${a}`:''}`;pointEnd=`Capítulo ${chapter}${z?` · pág. ${z}`:a?` · pág. ${a}`:''}`}else if(type==='pages'){pointStart=`Pág. ${a}`;pointEnd=`Pág. ${z}`}else if(type==='section')pointEnd=f.get('section');else if(type==='since')pointStart=f.get('lastPoint');else if(type==='custom')pointStart=pointEnd;let duration=f.get('durationMinutes')||'';if(!duration&&f.get('startedAt')&&f.get('endedAt')){const [ah,am]=f.get('startedAt').split(':').map(Number),[zh,zm]=f.get('endedAt').split(':').map(Number);duration=Math.max(0,zh*60+zm-ah*60-am)}return {sessionType:type,chapter,pageStart:a,pageEnd:z,page:z||a,section:f.get('section')||'',pointStart,pointEnd,startedAt:f.get('startedAt')||'',endedAt:f.get('endedAt')||'',durationMinutes:duration,plot:f.get('plot')||'',impression:f.get('impression')||'',context:f.get('context')||'',characterIds:f.getAll('characterIds'),relationshipIds:f.getAll('relationshipIds'),quoteIds:f.getAll('quoteIds')}}
function attachSessionItems(f,s){const b=active(),point=s.pointEnd||s.pointStart,chapter=s.chapter||'',newCharacter=f.get('newCharacterName').trim();if(newCharacter){const c={id:uid(),name:newCharacter,shortName:'',description:'',firstChapter:chapter,discoveryPoint:point,sessionId:s.id};b.characters.push(c);s.characterIds.push(c.id)}const from=f.get('newRelFrom'),to=f.get('newRelTo'),label=f.get('newRelType');if(from&&to&&from!==to&&label){const info=inferRel(label),r={id:uid(),from,to,items:[{label,mode:info.mode,category:info.category}],types:[label],chapter,discoveryPoint:point,sessionId:s.id};b.relationships.push(r);s.relationshipIds.push(r.id)}const text=f.get('newQuoteText').trim();if(text){const q={id:uid(),text,chapter,page:s.page||'',reason:'Importante para la trama',note:'',sessionId:s.id,discoveryPoint:point};b.quotes.push(q);s.quoteIds.push(q.id)}}
function renderSessions(){if(!requireBook())return;const b=active();document.getElementById('app').innerHTML=`<div class="section-title"><div><h2>📖 Sesiones de lectura</h2><div class="muted">${esc(b.title)} · ${b.sessions.length} sesión(es)</div></div><button class="primary" onclick="newSession()">+ Nueva sesión</button></div>${b.sessions.length?`<div class="list">${b.sessions.slice().reverse().map(s=>`<div class="card"><h3>${esc(SESSION_TYPES[s.sessionType]||'Sesión')} · ${esc(sessionPoint(s))}</h3><div class="muted">${esc(s.date)}${s.durationMinutes?` · ${esc(s.durationMinutes)} min`:''}</div>${s.plot||s.summary?`<p><strong>Trama:</strong> ${esc((s.plot||s.summary).slice(0,180))}</p>`:''}<div class="actions"><button class="secondary" onclick="viewSession('${s.id}')">Abrir</button><button class="secondary" onclick="editSession('${s.id}')">Editar</button><button class="danger" onclick="deleteSession('${s.id}')">Eliminar</button></div></div>`).join('')}</div>`:`<div class="empty">Aún no has registrado una sesión.</div>`}`}
function newSession(){modal(sessionForm('Nueva sesión de lectura'))}
function createSession(e){e.preventDefault();const f=new FormData(e.target),s={id:f.get('sessionId'),date:new Date().toLocaleString('es-CR'),createdAt:new Date().toISOString(),...sessionData(f)};attachSessionItems(f,s);active().sessions.push(s);save();close();renderSessions();toast('Sesión guardada')}
function editSession(id){const s=active().sessions.find(x=>x.id===id);if(s)modal(sessionForm('Editar sesión',s))}
function updateSession(e,id){e.preventDefault();const f=new FormData(e.target),s=active().sessions.find(x=>x.id===id);if(!s)return;Object.assign(s,sessionData(f));attachSessionItems(f,s);save();close();renderSessions();toast('Sesión actualizada')}
function deleteSession(id){if(!confirm('¿Eliminar esta sesión? Los elementos asociados se conservarán.'))return;active().sessions=active().sessions.filter(s=>s.id!==id);save();renderSessions();toast('Sesión eliminada')}
function viewSession(id){const b=active(),s=b.sessions.find(x=>x.id===id);if(!s)return;const chars=sessionItems(b,s.characterIds,'characters').map(x=>esc(x.name)).join(' · ')||'Sin personajes asociados',rels=sessionItems(b,s.relationshipIds,'relationships').map(relLabels).join(' · ')||'Sin relaciones asociadas',quotes=sessionItems(b,s.quoteIds,'quotes').map(x=>esc(x.text)).join('<br>');modal(`<h2>${esc(SESSION_TYPES[s.sessionType]||'Sesión')}</h2><div class="muted">${esc(s.date)} · ${esc(sessionPoint(s))}</div>${s.plot?`<p><strong>📖 Trama</strong><br>${esc(s.plot)}</p>`:''}<p><strong>👥 Personajes</strong><br>${chars}</p><p><strong>🔗 Relaciones</strong><br>${rels}</p>${s.context?`<p><strong>📍 Contexto</strong><br>${esc(s.context)}</p>`:''}${s.impression?`<p><strong>💭 Mi impresión</strong><br>${esc(s.impression)}</p>`:''}${quotes?`<p><strong>💬 Fragmentos</strong><br>${quotes}</p>`:''}<div class="actions"><button class="secondary" onclick="editSession('${s.id}')">Editar</button><button class="danger" onclick="deleteSession('${s.id}')">Eliminar</button></div>`) }
function renderRecap(){if(!requireBook())return;const b=active(),last=b.sessions.at(-1),chars=last?sessionItems(b,last.characterIds,'characters'):[],rels=last?sessionItems(b,last.relationshipIds,'relationships'):[],quotes=last?sessionItems(b,last.quoteIds,'quotes'):[];const recent=last?`<div class="card hero"><h2>🧠 ¿Dónde estabas?</h2><div class="stat">${esc(sessionPoint(last))}</div><p>${esc(last.date)}</p>${last.plot||last.summary?`<p><strong>Trama:</strong><br>${esc(last.plot||last.summary)}</p>`:''}${chars.length?`<p><strong>Personajes relevantes:</strong> ${chars.map(c=>esc(c.name)).join(' · ')}</p>`:''}${rels.length?`<p><strong>Últimas relaciones:</strong> ${rels.map(relLabels).join(' · ')}</p>`:''}${last.impression||last.note?`<p><strong>Tu impresión:</strong><br>${esc(last.impression||last.note)}</p>`:''}${quotes.length?`<p><strong>Fragmentos asociados:</strong><br>${quotes.map(q=>esc(q.text)).join('<br>')}</p>`:''}</div>`:`<div class="card hero"><h2>🧠 Tu punto de partida</h2><p>Aún no has registrado una sesión de lectura.</p><button class="primary" onclick="newSession()">Registrar dónde estoy</button></div>`;document.getElementById('app').innerHTML=`<div class="section-title"><div><h2>🧠 Retomar lectura</h2><div class="muted">${esc(b.title)} · ${esc(b.author||'')}</div></div></div>${recent}<div class="grid"><div class="card"><h3>👥 Personajes</h3><div class="stat">${b.characters.length}</div><button class="secondary" onclick="view('characters')">Ver personajes</button></div><div class="card"><h3>💬 Fragmentos</h3><div class="stat">${b.quotes.length}</div><button class="secondary" onclick="view('quotes')">Ver fragmentos</button></div><div class="card"><h3>📖 Sesiones</h3><div class="stat">${b.sessions.length}</div><button class="secondary" onclick="view('sessions')">Ver sesiones</button></div></div>`}

// --- Session relationship editor -------------------------------------------
function sessionRelationRow(s,r){const b=active(),a=b.characters.find(c=>c.id===r.from),z=b.characters.find(c=>c.id===r.to),sym=(r.items||[]).some(i=>i.mode==='symmetric'),dir=sym?'↔':'→';return `<div class="relationship"><input type="hidden" name="relationshipIds" value="${r.id}"><span class="node">${esc(a?.name||'?')}</span><span class="arrow">— ${relLabels(r)} ${dir}</span><span class="node">${esc(z?.name||'?')}</span><div class="rel-actions"><button type="button" class="secondary" onclick="editSessionRelationship('${s.id}','${r.id}')">Editar</button><button type="button" class="danger" onclick="deleteSessionRelationship('${s.id}','${r.id}')">Eliminar</button></div></div>`}
function draftRelationRow(){const b=active();return `<div class="item session-relation-draft"><div class="grid"><div class="field"><label>Personaje A</label><select name="draftFrom"><option value="">Selecciona</option>${b.characters.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Personaje B</label><select name="draftTo"><option value="">Selecciona</option>${b.characters.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div></div><div class="field"><label>Relación o relaciones</label><div class="check-grid">${relTypes.map(x=>`<label class="check-option"><input type="checkbox" name="draftTypes" value="${esc(x)}">${esc(x)}</label>`).join('')}</div></div><div class="grid"><div class="field"><label>Otra relación personalizada</label><input name="draftCustom" placeholder="Opcional"></div><div class="field"><label>Dirección personalizada</label><select name="draftCustomMode"><option value="directed">A → B</option><option value="symmetric">A ↔ B</option></select></div></div><button type="button" class="danger" onclick="this.closest('.session-relation-draft').remove()">Eliminar</button></div>`}
function addSessionRelation(){const target=document.getElementById('sessionRelationshipDrafts');if(target)target.insertAdjacentHTML('beforeend',draftRelationRow())}
function sessionRelationsSection(s){const b=active(),existing=sessionItems(b,s.relationshipIds,'relationships');return `<div class="field"><label>🔗 Relaciones descubiertas</label><div class="list">${existing.map(r=>sessionRelationRow(s,r)).join('')}</div><button type="button" class="secondary" onclick="addSessionRelation()">+ Agregar relación</button><div id="sessionRelationshipDrafts" class="list" style="margin-top:10px"></div></div>`}
function sessionForm(title,s={}){const b=active(),type=s.sessionType||'chapter',id=s.id||uid();return `<h2>${title}</h2><form onsubmit="${s.id?`updateSession(event,'${s.id}')`:'createSession(event)'}"><input type="hidden" name="sessionId" value="${id}"><div class="field"><label>Tipo de sesión</label><select name="sessionType" onchange="updateSessionTypeFields(this.value)">${Object.entries(SESSION_TYPES).map(([k,v])=>`<option value="${k}" ${k===type?'selected':''}>${v}</option>`).join('')}</select></div><div id="sessionTypeFields">${sessionTypeFields(type,s)}</div><div class="grid"><div class="field"><label>Hora de inicio</label><input name="startedAt" type="time" value="${esc(s.startedAt||'')}"></div><div class="field"><label>Hora final</label><input name="endedAt" type="time" value="${esc(s.endedAt||'')}"></div><div class="field"><label>Duración (minutos)</label><input name="durationMinutes" type="number" min="0" value="${esc(s.durationMinutes||'')}"></div></div><div class="field"><label>📖 Trama — ¿Qué ocurrió?</label><textarea name="plot">${esc(s.plot||s.summary||'')}</textarea></div>${sessionChecks('characterIds',b.characters,s.characterIds,'👥 Personajes relevantes',x=>x.name)}<div class="field"><label>Crear personaje desde esta sesión</label><input name="newCharacterName" placeholder="Nombre (opcional)"></div>${sessionRelationsSection(s)}<div class="field"><label>📍 Lugares / contexto</label><textarea name="context" placeholder="Ej.: Can Gispert">${esc(s.context||'')}</textarea></div>${sessionChecks('quoteIds',b.quotes,s.quoteIds,'💬 Fragmentos',x=>x.text.slice(0,80))}<div class="field"><label>Crear fragmento desde esta sesión</label><textarea name="newQuoteText"></textarea></div><div class="field"><label>💭 Mi impresión</label><textarea name="impression">${esc(s.impression||s.note||'')}</textarea></div><button class="primary">Guardar sesión</button></form>`}
function attachSessionItems(f,s,form){const b=active(),point=s.pointEnd||s.pointStart,chapter=s.chapter||'',newCharacter=f.get('newCharacterName').trim();if(newCharacter){const c={id:uid(),name:newCharacter,shortName:'',description:'',firstChapter:chapter,discoveryPoint:point,sessionId:s.id};b.characters.push(c);s.characterIds.push(c.id)}const rows=[...(form?.querySelectorAll('.session-relation-draft')||[])];rows.forEach(row=>{const from=row.querySelector('[name="draftFrom"]').value,to=row.querySelector('[name="draftTo"]').value,labels=[...row.querySelectorAll('[name="draftTypes"]:checked')].map(x=>x.value),custom=row.querySelector('[name="draftCustom"]').value.trim();if(custom)labels.push(custom);if(!from||!to||from===to||!labels.length)return;const customMode=row.querySelector('[name="draftCustomMode"]').value,items=[...new Set(labels)].map(label=>({label,mode:label===custom?customMode:inferRel(label).mode,category:label===custom?'Otra':inferRel(label).category})),r={id:uid(),from,to,items,types:items.map(i=>i.label),chapter,discoveryPoint:point,sessionId:s.id};b.relationships.push(r);s.relationshipIds.push(r.id)});const text=f.get('newQuoteText').trim();if(text){const q={id:uid(),text,chapter,page:s.page||'',reason:'Importante para la trama',note:'',sessionId:s.id,discoveryPoint:point};b.quotes.push(q);s.quoteIds.push(q.id)}}
function createSession(e){e.preventDefault();const f=new FormData(e.target),s={id:f.get('sessionId'),date:new Date().toLocaleString('es-CR'),createdAt:new Date().toISOString(),...sessionData(f)};attachSessionItems(f,s,e.target);active().sessions.push(s);save();close();renderSessions();toast('Sesión guardada')}
function updateSession(e,id){e.preventDefault();const f=new FormData(e.target),s=active().sessions.find(x=>x.id===id);if(!s)return;const data=sessionData(f);data.relationshipIds=[...new Set([...(s.relationshipIds||[]),...data.relationshipIds])];Object.assign(s,data);attachSessionItems(f,s,e.target);save();close();renderSessions();toast('Sesión actualizada')}
function editSessionRelationship(sessionId,relationId){const r=active().relationships.find(x=>x.id===relationId);if(!r)return;const html=relationshipForm('Editar relación descubierta',r).replace(`updateRelationship(event,'${relationId}')`,`updateSessionRelationship(event,'${sessionId}','${relationId}')`);modal(html)}
function updateSessionRelationship(e,sessionId,relationId){e.preventDefault();const f=new FormData(e.target),data=getRelationshipData(f);if(data.from===data.to){toast('Una relación no puede apuntar al mismo personaje');return}const r=active().relationships.find(x=>x.id===relationId);if(!r)return;Object.assign(r,data);save();close();editSession(sessionId);toast('Relación actualizada en toda la red')}
function deleteSessionRelationship(sessionId,relationId){if(!confirm('¿Eliminar esta relación de la sesión y de la red global?'))return;const b=active();b.relationships=b.relationships.filter(r=>r.id!==relationId);b.sessions.forEach(s=>s.relationshipIds=(s.relationshipIds||[]).filter(id=>id!==relationId));save();editSession(sessionId);toast('Relación eliminada de la red global')}

// --- Relationship validation and diagnostics --------------------------------
let pendingRelationship=null;
function normalizeRelationText(value){return String(value||'').trim().toLocaleLowerCase('es').replace(/\s+/g,' ').replace(/\s*·\s*/g,' · ')}
function relationshipSignature(r){return [r.from||'',r.to||'',...(r.items||[]).map(i=>`${normalizeRelationText(i.label)}|${i.mode||''}|${normalizeRelationText(i.category)}`).sort()].join('||')}
function findMatchingRelationship(data,excludeId){const signature=relationshipSignature(data);return active().relationships.find(r=>r.id!==excludeId&&relationshipSignature(r)===signature)}
function saveRelationshipData(data){active().relationships.push({id:uid(),...data});save();close();renderCharacters();toast('Conexión creada')}
function createRelationship(e){e.preventDefault();const data=getRelationshipData(new FormData(e.target));if(data.from===data.to){modal('<h2>Relación no válida</h2><p class="muted">Un personaje no puede relacionarse consigo mismo.</p>');return}const duplicate=findMatchingRelationship(data);if(!duplicate){saveRelationshipData(data);return}pendingRelationship=data;modal(`<h2>Posible relación duplicada</h2><p class="muted">Ya existe una relación igual entre estos personajes.</p><div class="actions"><button class="secondary" onclick="close()">Cancelar</button><button class="secondary" onclick="resolveDuplicateRelationship('edit','${duplicate.id}')">Editar relación existente</button><button class="primary" onclick="resolveDuplicateRelationship('create')">Crear de todos modos</button></div>`) }
function resolveDuplicateRelationship(action,id){const data=pendingRelationship;pendingRelationship=null;if(action==='edit'){close();editRelationship(id);return}if(action==='create'&&data)saveRelationshipData(data)}
function relationshipIssues(){const b=active(),ids=new Set(b.characters.map(c=>c.id)),groups=new Map();b.relationships.forEach(r=>{const key=relationshipSignature(r);groups.set(key,[...(groups.get(key)||[]),r])});return {duplicates:[...groups.values()].filter(group=>group.length>1),unknown:b.relationships.filter(r=>!hasKnownChapter(r.chapter)),invalid:b.relationships.filter(r=>!ids.has(r.from)||!ids.has(r.to)||!r.from||!r.to)}}
function relationshipDiagnostics(){const b=active(),issues=relationshipIssues(),name=id=>b.characters.find(c=>c.id===id)?.name||'?';const duplicateRows=issues.duplicates.length?issues.duplicates.map(group=>`<div class="item"><strong>${esc(name(group[0].from))} → ${esc(relLabels(group[0]))} → ${esc(name(group[0].to))}</strong><div class="muted">${group.length} coincidencias; revisa cada una antes de eliminar.</div><div class="actions">${group.map(r=>`<button class="danger" onclick="removeDiagnosedRelationship('${r.id}')">Eliminar ${esc(r.id)}</button>`).join('')}</div></div>`).join(''):'<div class="muted">No se detectaron duplicados.</div>';modal(`<h2>Diagnóstico de relaciones</h2><div class="map-stats"><span class="map-stat">Duplicados: ${issues.duplicates.length}</span><span class="map-stat">Capítulo desconocido: ${issues.unknown.length}</span><span class="map-stat">Personajes inexistentes: ${issues.invalid.length}</span></div><h3>Duplicados posibles</h3>${duplicateRows}<h3>Capítulo desconocido</h3><div class="muted">${issues.unknown.map(r=>esc(`${name(r.from)} → ${relLabels(r)} → ${name(r.to)}`)).join('<br>')||'Ninguno'}</div><h3>Referencias inválidas</h3><div class="muted">${issues.invalid.map(r=>esc(r.id)).join(' · ')||'Ninguna'}</div>`) }
function removeDiagnosedRelationship(id){if(!confirm('¿Eliminar esta relación global?'))return;const b=active();b.relationships=b.relationships.filter(r=>r.id!==id);b.sessions.forEach(s=>s.relationshipIds=(s.relationshipIds||[]).filter(rid=>rid!==id));save();relationshipDiagnostics();toast('Relación eliminada')}
function viewSession(id){const b=active(),s=b.sessions.find(x=>x.id===id);if(!s)return;const chars=sessionItems(b,s.characterIds,'characters').map(x=>esc(x.name)).join(' · ')||'Sin personajes asociados',rels=sessionItems(b,s.relationshipIds,'relationships'),quotes=sessionItems(b,s.quoteIds,'quotes').map(x=>esc(x.text)).join('<br>');modal(`<h2>${esc(SESSION_TYPES[s.sessionType]||'Sesión')}</h2><div class="muted">${esc(s.date)} · ${esc(sessionPoint(s))}</div>${s.plot?`<p><strong>📖 Trama</strong><br>${esc(s.plot)}</p>`:''}<p><strong>👥 Personajes</strong><br>${chars}</p><div class="field"><label>🔗 Relaciones descubiertas</label><div class="list">${rels.map(r=>sessionRelationRow(s,r)).join('')||'<div class="muted">Sin relaciones asociadas</div>'}</div></div>${s.context?`<p><strong>📍 Contexto</strong><br>${esc(s.context)}</p>`:''}${s.impression?`<p><strong>💭 Mi impresión</strong><br>${esc(s.impression)}</p>`:''}${quotes?`<p><strong>💬 Fragmentos</strong><br>${quotes}</p>`:''}<div class="actions"><button class="secondary" onclick="editSession('${s.id}')">Editar sesión</button><button class="danger" onclick="deleteSession('${s.id}')">Eliminar sesión</button></div>`) }

// --- PWA -------------------------------------------------------------------
window.renderMap=renderMap;window.characterDuplicateDiagnostics=characterDuplicateDiagnostics;window.compareCharacters=compareCharacters;window.openCharacterMerge=openCharacterMerge;window.setMergeSource=setMergeSource;window.mergeCharacters=mergeCharacters;window.newBook=newBook;window.createBook=createBook;window.selectBook=selectBook;window.editBook=editBook;window.updateBook=updateBook;window.view=view;window.newCharacter=newCharacter;window.createCharacter=createCharacter;window.editCharacter=editCharacter;window.updateCharacter=updateCharacter;window.newRelationship=newRelationship;window.createRelationship=createRelationship;window.resolveDuplicateRelationship=resolveDuplicateRelationship;window.relationshipDiagnostics=relationshipDiagnostics;window.removeDiagnosedRelationship=removeDiagnosedRelationship;window.editRelationship=editRelationship;window.updateRelationship=updateRelationship;window.deleteRelationship=deleteRelationship;window.newQuote=newQuote;window.createQuote=createQuote;window.deleteQuote=deleteQuote;window.newSession=newSession;window.createSession=createSession;window.editSession=editSession;window.updateSession=updateSession;window.deleteSession=deleteSession;window.viewSession=viewSession;window.updateSessionTypeFields=updateSessionTypeFields;window.addSessionRelation=addSessionRelation;window.editSessionRelationship=editSessionRelationship;window.updateSessionRelationship=updateSessionRelationship;window.deleteSessionRelationship=deleteSessionRelationship;window.setMapViewMode=setMapViewMode;window.setMapFocus=setMapFocus;window.setMapLevel=setMapLevel;window.setMapScope=setMapScope;window.toggleMapCategory=toggleMapCategory;window.resetMapView=resetMapView;window.recenterMap=recenterMap;window.reorganizeNetwork=reorganizeNetwork;window.mapZoom=mapZoom;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.getElementById('installBtn').classList.remove('hidden')});
document.getElementById('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
render('home');
